import type { Masterpiece } from "./masterpiece";

export const masterpieces: Masterpiece[] = [
  {
    id: 1,
    name: "Two Birds",
    releaseDate: new Date(),
    price: 10,
    category: "Realism",
    url: "https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image.jpg",
  },
  {
    id: 2,
    name: "Smurf vs Lasagnas",
    releaseDate: new Date(),
    price: 20,
    category: "Abstract",
    url: "https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-1.jpg",
  },
  {
    id: 3,
    name: "The Little Girl",
    releaseDate: new Date(),
    price: 30,
    category: "Realism",
    url: "https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-2.jpg",
  },
  {
    id: 4,
    name: "The Sea",
    releaseDate: new Date(),
    price: 40,
    category: "Abstract",
    url: "https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-3.jpg",
  },
  {
    id: 5,
    name: "The Bird",
    releaseDate: new Date(),
    price: 50,
    category: "Realism",
    url: "https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-4.jpg",
  },
  {
    id: 6,
    name: "The Bird",
    releaseDate: new Date(),
    price: 50,
    category: "Realism",
    url: "https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-5.jpg",
  },
  {
    id: 7,
    name: "The Bird",
    releaseDate: new Date(),
    price: 50,
    category: "Realism",
    url: "https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-6.jpg",
  },
  {
    id: 8,
    name: "The Bird",
    releaseDate: new Date(),
    price: 50,
    category: "Realism",
    url: "https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-7.jpg",
  },
  {
    id: 9,
    name: "The Bird",
    releaseDate: new Date(),
    price: 50,
    category: "Realism",
    url: "https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-8.jpg",
  },
  {
    id: 10,
    name: "The Bird",
    releaseDate: new Date(),
    price: 50,
    category: "Realism",
    url: "https://flowbite.s3.amazonaws.com/docs/gallery/masonry/image-9.jpg",
  },
];
